"""Initial migration

Revision ID: b024c68c8828
Revises: 
Create Date: 2026-01-31 21:01:31.078042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b024c68c8828'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall', schema=None) as batch_op:
        # batch_op.drop_column('is_ground_floor')
        pass

    with op.batch_alter_table('student', schema=None) as batch_op:
        # batch_op.drop_column('is_physically_challenged')
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_physically_challenged', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('hall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ground_floor', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
